FROM rust:latest AS builder
RUN cargo install cargo-afl

ADD . /gjson.rs
WORKDIR /gjson.rs/extra/fuzz
RUN cargo afl build --release

FROM ubuntu:22.04
COPY --from=builder /gjson.rs/extra/fuzz/target/release/fuzz /fuzz
